services:
  needledrop:
    image: roymond/needledrop:latest
    env_file:
      - .env
    networks:
      - container-dmz
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=container-dmz"
      - "traefik.http.routers.records.rule=Host(`records.roymond.net`)"
      - "traefik.http.routers.records.entrypoints=websecure"
      - "traefik.http.routers.records.tls.certresolver=production"
      - "traefik.http.services.records.loadbalancer.server.port=3345"
    restart: always

networks:
  container-dmz:
    external: true
